### ISSUE TITLE
HttpConnection should be replaced in ConnManager when Response contains "Connection: Closed"

### ISSUE THREAD

**Issue by alexw91** [awslabs/aws-c-http#139]
Don't vend a HttpConnection to new Request that has had a "Connection: Closed" Header in either request or response. 

The HttpConnection should be replaced with a new HttpConnection in ConnManager when a HttpRequest or HttpResponse contains "Connection: Closed" Header.

**Comment by graebm** [comment]
The `aws_http_connection` needs support the "Connection: close" header as described in [RFC 7230](https://httpwg.org/specs/rfc7230.html#rfc.section.6.1).

Once that's in, the connection will be closed upon completion of the response. The `aws_http_connection_manager` shouldn't need any changes. It will detect that the connection has closed and acquire a new one to replace it.

**Comment by bretambrose** [comment]
Close support should now be working per https://github.com/awslabs/aws-c-http/commit/0d8d67359e0af82a7c6e28ad19fc0e49fc2787a0
