### ISSUE TITLE
[Improvement suggestion] Update README.md with some details such as library dependencies and how to build it

### ISSUE THREAD

**Issue by disa6302** [awslabs/aws-c-http#182]
Hello,

Can the README.md be updated with some details about the library and perhaps some details on what the dependencies are and how to build it? 

It could be straight forward, but details would always be useful.

**Comment by bretambrose** [comment]
Thanks for the feedback.   Our first GA use case was using the aws-c-* library suite as a whole from the aws-crt-* language bindings, but better (pick-and-choose) usage instructions are definitely something we need to provide.

**Comment by TingDaoK** [comment]
It's updated. https://github.com/awslabs/aws-c-http/pull/262
