### ISSUE TITLE
Add option to force tunnelling for proxied plaintext connections

### ISSUE THREAD

**Issue by adamthom-amzn** [awslabs/aws-c-http#193]
Similar to curl's `--proxytunnel` option, it would be convenient if the HTTP proxy options included a flag to force tunneling for all proxied calls (via CONNECT).  Current behavior is to use CONNECT only for TLS requests.  Some additional context from one of our users:

> we pushed for CONNECT request to be the primary method of establishing proxy connections in the Netty4 client because it provides cleaner protocol semantics, is applicable to more protocols (you can establish a TCP tunnel for any protocol using a CONNECT request), and in general makes the proxy connecting code easier to support.  We've thought about deprecating absolute resource handshakes for a while.  We implemented it to support [the current] client's proxy behavior.  However, this handshake type forces [our product] to function as an L7 proxy instead of an L4 proxy as the contents of the HTTP request must be buffered and sent to the destination.  If you have to choose between one mechanism or another for establishing proxy connections I would side toward CONNECT requests for everything as it supports both HTTP and HTTPS.

**Comment by bretambrose** [comment]
Support for this was added recently (https://github.com/awslabs/aws-c-http/blob/main/include/aws/http/proxy.h#L37).  It's currently bound out in the C++ CRT and the other CRTs will follow shortly over the next few weeks.
