### ISSUE TITLE
Double task scheduling when aws_http1_stream_write_chunk() is used.

### ISSUE THREAD

**Issue by chehefen** [awslabs/aws-c-http#270]
aws_http1_stream_write_chunk() triggers outgoing_stream_task to be scheduled here: https://github.com/awslabs/aws-c-http/blob/master/source/h1_connection.c#L441. However, outgoing_stream_task could also be scheduled here: https://github.com/awslabs/aws-c-http/blob/master/source/h1_connection.c#L870. These two together can cause the double scheduling of the outgoing_stream_task and cause some linklist assertion to fail when aws_http1_stream_write_chunk is called. In my case, second aws_http1_stream_write_chunk() call fails after first aws_http1_stream_write_chunk call has completed successfully.

**Comment by graebm** [comment]
Fixed in master!
thanks for the excellent diagnosis
