### ISSUE TITLE
Proposal - Readability Improvement - Avoid rename of aws-c-io functions

### ISSUE THREAD

**Issue by cobookman** [awslabs/aws-c-http#358]
### Proposal
Changing these lines in [connection_manager.c#L44-L51](
https://github.com/awslabs/aws-c-http/blob/02406e1998e3c4a468e99a7cd6c6b23b58fee7cd/source/connection_manager.c#L44-L51)
```
static struct aws_http_connection_manager_system_vtable s_default_system_vtable = {
    .create_connection = aws_http_client_connect,
    .release_connection = aws_http_connection_release,
    .close_connection = aws_http_connection_close,
    .is_connection_available = aws_http_connection_new_requests_allowed,
    .get_monotonic_time = aws_high_res_clock_get_ticks,
    .is_callers_thread = aws_channel_thread_is_callers_thread,
    .connection_get_channel = aws_http_connection_get_channel,
};
```

TO:
```
static struct aws_http_connection_manager_system_vtable s_default_system_vtable = {
    .aws_http_client_connect = aws_http_client_connect,
    .aws_http_connection_release = aws_http_connection_release,
    .aws_http_connection_close = aws_http_connection_close,
    .aws_http_connection_new_requests_allowed = aws_http_connection_new_requests_allowed,
    .aws_high_res_clock_get_ticks = aws_high_res_clock_get_ticks,
    .aws_channel_thread_is_callers_thread = aws_channel_thread_is_callers_thread,
    .aws_http_connection_get_channel = aws_http_connection_get_channel,
};
```

### Rational:
Improve readability of the codebase and make it easier to understand call paths between aws-c-http and aws-c-io.

The current renaming of functions makes it difficult to parse function call paths and to perform searches for where `aws_http_*` is being invoked across the aws c/cpp SDKs.

**Comment by yasminetalby** [comment]
Hello @cobookman ,

Thank you very much for your submission and feedback.
My apologies for the delay of answer on this issue. We are open to this change if you would like to make a PR for it!

Best regards,

Yasmine

**Comment by graebm** [comment]
Done
