### ISSUE TITLE
aws_http_message_request_data allow query strings in path

### ISSUE THREAD

**Issue by JustinBerger** [awslabs/aws-c-http#401]
Currently, if the http request message path contains a query string it fails with AWS_ERROR_HTTP_INVALID_PATH.
Alternative would be to have an additional field(s) to store query strings.

Found this while trying to implement a call to download s3 file, using pre-signed url.

Steps to reproduce, http1 request with `https://example.com/file?p1=1&p2=a`

I'd rather not have to include a separate http client implementation for pre-signed s3 requests within my IoT device.

**Comment by graebm** [comment]
Query strings are supported. They should be part of the path
```
/**
 * Set the path-and-query value (request messages only).
 * The request makes its own copy of the underlying string.
 */
AWS_HTTP_API
int aws_http_message_set_request_path(struct aws_http_message *request_message, struct aws_byte_cursor path);
```

You would set it like this:
```
aws_http_message_set_request_path(request, aws_byte_cursor_from_c_str("/file?p1=1&p2=a")
```

You can quickly test this yourself by building this library with `BUILD_TESTING=ON`, which results in the [elasticurl](https://github.com/awslabs/aws-c-http/tree/main/bin/elasticurl) sample app getting built. Here I am running it and passing along a query string:

```
$ ./elasticurl/elasticurl "https://example.com/file?p1=1&p2=a"
<!doctype html>
<html>
<head>
    <title>Example Domain</title>
...blahblahblah...
</html>
```
