### ISSUE TITLE
SOCKS5 proxy support

### ISSUE THREAD

**Issue by timbz** [awslabs/aws-c-http#484]
### Describe the feature

Add support for SOCKS5 proxy

### Use Case

We are planning to use the AWS CRT libs in an automotive project. Due to the highly regulated environment, backend connection is only allowed though a (in-vehicle) SOCKS5 proxy. 

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by timbz** [comment]
We do have technical account managers

**Comment by bretambrose** [comment]
Your best bet is to have your TAM make a feature request with the CRT/IoT SDK teams.
